### ISSUE TITLE
Not all models

### ISSUE THREAD

**Issue by Mugaduka** [WangHelin1997/SoloAudio#6]
HI
I am trying to run example 
`tse_languageTSE.py --output_dir './output-languageTSE/' --mixture './demo/1_mix.wav' --enrollment 'Acoustic guitar'`

but FileNotFoundError: [Errno 2] No such file or directory: './pretrained_models/config.json' error happens. Exeption starts from loading vae. Using config from stable_audio_vae/configs not helps.

Could you please share vae config opportuned to https://huggingface.co/westbrook/SoloAudio/tree/main/audio-vae.pt?

**Comment by WangHelin1997** [comment]
Hi,

Thanks for your interest in our work! It is now available at [https://github.com/WangHelin1997/SoloAudio/blob/main/pretrained_models/config.json](https://github.com/WangHelin1997/SoloAudio/blob/main/pretrained_models/config.json).
